#!/bin/bash -l  
#SBATCH -N 1 
#SBATCH -t 4:00:00 
#SBATCH -C gpu
#SBATCH -G 4
# -G 1 soap_data_hyper_M5_MOF MOF_data_hyper_M4
#SBATCH -J bulk_data_M6 
#SBATCH -c 10

#srun --pty python main.py --data_path=../Data_current/oqmd_data --train_ratio=0.25 --val_ratio=0.3 --test_ratio=0.3 --format=db
#srun --pty python main.py --data_path=../Data_current/oqmd_data_small --format=db --seed=200656
#srun --pty python main.py --data_path=../Data_current/bulk_data

#srun --pty python main.py --data_path=../Data_current/bulk_data --model=SchNet --run_mode=CV
#srun --pty python main.py --data_path=../Data_current/oqmd_data_small --format=db --model=MPNN

#srun --pty python main.py --data_path=../Data_current/MP_data --format=db --epochs=50 --reprocess=False
#srun --pty python main.py --data_path=../Data_current/MOF_data_v2 --format=cif --epochs=200 --load_model=False --save_model=False --reprocess=False
srun --pty python main.py --data_path=../Data_current/MOF_data_v2 --format=cif --epochs=200 --load_model=True --save_model=False --reprocess=False
#srun --pty python main.py --data_path=../Data_current/bulk_data --format=json